name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      PROJECT_REPOSITORY: Kitware/CMake
      PROJECT_VERSION: v3.21.7
      PROJECT_PATH: cmake
      PROJECT_BIN: cmake

    steps:
      - name: Windows Config
        shell: pwsh
        run: |
          git config --system core.longpaths true
          echo "Enabled long paths in git"

          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          echo "Enabled long paths in registry"

          $git_link = "C:\Program Files\Git\usr\bin\link.exe"
          if (Test-Path $git_link) {
              Rename-Item $git_link "_link.exe"
          }
          echo "Removed link.exe in git"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.29
          arch: x64
          sdk: 10.0.19041.0

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.19.x"

      - name: Checkout ${{ env.PROJECT_PATH }}
        uses: actions/checkout@v6
        with:
          repository: ${{ env.PROJECT_REPOSITORY }}
          ref: refs/tags/${{ env.PROJECT_VERSION }}
          path: ${{ env.PROJECT_PATH }}

      - name: Build
        shell: pwsh
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          cmake -B build/release `
          -G "NMake Makefiles" `
          -T v142 `
          -A x64 `
          -D CMAKE_BUILD_TYPE=Release `
          -DCMAKE_CXX_FLAGS="/arch:AVX2 /MD /MP /Oi /Os /Gy /GL /Gw /fp:fast /GR- /GS- /DNDEBUG" `
          -DCMAKE_EXE_LINKER_FLAGS="/LTCG /MANIFEST:NO /MERGE:_RDATA=.rdata /OPT:REF /OPT:ICF"

          cmake --build build/release

      - name: Archive
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.PROJECT_BIN }}_${{ runner.os }}
          path: |
            ${{ env.PROJECT_PATH }}/target/release/*.so
            ${{ env.PROJECT_PATH }}/target/release/*.dll

            ${{ env.PROJECT_PATH }}/target/release/${{ env.PROJECT_BIN }}
            ${{ env.PROJECT_PATH }}/target/release/${{ env.PROJECT_BIN }}.exe
